@HostAddress = http://localhost:5066/api/Weather

GET {{HostAddress}}/weatherforecast/
Accept: application/json

### GET ALL 
GET {{HostAddress}}

### GET By ID
GET {{HostAddress}}/1

### GET By City 
GET {{HostAddress}}/city/Ottumwa
